### PR TITLE
Catch the error where experiment has no secondary accessions provided in idf file

### LINKED ISSUE #184: Supplyment Information page not working on bulk with E-PROT experiments
According to @irisdianauy report.

Many E-PROT experiments have nothing under the Supplementary Information tab. Doesn’t seem like by design, because when you do click on the Supplementary Information tab of one such experiment, all the other tabs disappear (as opposed to just having an empty tab).  Examples are [E-PROT-13](https://wwwdev.ebi.ac.uk/gxa/experiments/E-PROT-13/Results), [E-PROT-106](https://wwwdev.ebi.ac.uk/gxa/experiments/E-PROT-106/Results), [E-PROT-23](https://wwwdev.ebi.ac.uk/gxa/experiments/E-PROT-23/Results).

### PR DESCRIPTION
**Pull request by lingyun1010**
Manual checks

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

### CODE REVIEW

File: src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java [hunk 1]
```diff
@@ -39,10 +42,15 @@ public Function<HttpServletResponse, Void> stream(E experiment, final URI uri) {
...
-        return suppliers.stream()
-                .filter(eSupplier -> eSupplier.contentType().equals(contentType))
-                .flatMap(extractContentFromSupplier(experiment))
-                .collect(Collectors.toList());
+       try {
+           return   suppliers.stream()
+                    .filter(eSupplier -> eSupplier.contentType().equals(contentType))
+                    .flatMap(extractContentFromSupplier(experiment))
+                    .collect(Collectors.toList());
+        } catch(Exception e){
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java]: This looks like a too wide catch. Could we narrow it down and make it a bit more specific, please?
Thanks

P.S.: I am also wondering why are we throwing exception in the above code if there is no secondary exception. It is a bit strange to me. Probably we should return with an empty list or something relevant, but not an exception. And if we change that code to this, then we don't even need this `catch` block.

File: src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java [hunk 2]
```diff
@@ -39,10 +42,15 @@ public Function<HttpServletResponse, Void> stream(E experiment, final URI uri) {
...
+           LOGGER.info("Experiment: {} has no secondary accessions.", experiment.getAccession());
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java]: I think we could change this to `debug` level to not make our logger too chatty.

**Review by ke4 — CHANGES_REQUESTED** [review]
I added some request for consideration. We can discuss it tomorrow if it is not clear.
Thanks

**Comment by ke4** [comment]
@lingyun1010 With a little bit of debugging I found the root cause of the problem.
In the `LinkToPride` class we have these `private static final` fields:

```
    private static final Function<BaselineExperiment, String> formatLabel =
            e -> MessageFormat.format("PRIDE Archive: project {0}", e.getSecondaryAccessions().stream().findAny().get());
    private static final Function<BaselineExperiment, String> formatLink =
            e -> MessageFormat.format("https://www.ebi.ac.uk/pride/archive/projects/{0}", e.getSecondaryAccessions().stream().findAny().get());
```

This code suspects that we always have `secondaryAccession` for an experiment. Even IntelliJ marks the `get()` call and tells us: `If a value is present, returns the value, otherwise throws NoSuchElementException.`

So, I suggest to correct these lines and then we don't have to deal with a wrongly thrown exception.

If it is not clear, then we can discuss it tomorrow.

Thanks

**Comment by ke4** [comment]
By the way in these lines the `findAny()` call is a bit weird to me. 

```
 private static final Function<BaselineExperiment, String> formatLabel =
            e -> MessageFormat.format("PRIDE Archive: project {0}", e.getSecondaryAccessions().stream().findAny().get());
    private static final Function<BaselineExperiment, String> formatLink =
            e -> MessageFormat.format("https://www.ebi.ac.uk/pride/archive/projects/{0}", e.getSecondaryAccessions().stream().findAny().get());
```

From the JavaDoc: 
`The behaviour of this operation is explicitly nondeterministic; it is free to select any element in the stream. This is to allow for maximal performance in parallel operations; the cost is that multiple invocations on the same source may not return the same result. (If a stable result is desired, use findFirst() instead.)`

File: src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java [hunk 3]
```diff
@@ -22,7 +24,11 @@ public class LinkToPride extends ExternallyAvailableContent.Supplier<BaselineExp
 
     @Override
     public Collection<ExternallyAvailableContent> get(BaselineExperiment experiment) {
-        return singleton(new ExternallyAvailableContent(formatLink.apply(experiment), createIcon.apply(experiment)));
+        try {
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java]: I am sorry, but this is not the way to fix this bug.
We need to refactor this code to not throw this `NoSuchElementException` exception.
In my previous comment that I added to this ticket I already suggested the lines that we need to refactor. Those are the lines where we call a `get()` on an `Optional` without checking if it has any values.

File: src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java [hunk 4]
```diff
@@ -24,11 +24,8 @@ public class LinkToPride extends ExternallyAvailableContent.Supplier<BaselineExp
 
     @Override
     public Collection<ExternallyAvailableContent> get(BaselineExperiment experiment) {
-        try {
-            return   singleton(new ExternallyAvailableContent(formatLink.apply(experiment), createIcon.apply(experiment)));
-        } catch(NoSuchElementException e){
-            return Collections.emptyList();
-        }
+        return  experiment.getSecondaryAccessions().isEmpty() ? Collections.emptyList() :
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java]: Unfortunately, this is still not fixing the issue in line 18 and 20. 
`findAny()` is a non-deterministic method. Could be return any value from a collection.
Also, it would be better to just pass a String value to those variables (`formatLabel`, `formatLink` and `createIcon`) and get that string value in this current `get` method.
Thanks

Comment (lingyun1010) [reply src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java]: It did fix the issue actually and I tested locally which is working fine. We only call `formatLabel`, `formatLink` and `createIcon` when the `secondaryAccessions` is not empty so it wouldn't cause any issues to call `findAny()`. Please check it again or run locally to test. Thanks.

Comment (ke4) [reply src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java]: @lingyun1010 I understand that your changes is going to fix the bug, but we are also trying to clean the code where we can. I would like to leave a cleaner code that we had before.
Please, read my suggestions above. That should help you how to do it.
Thanks for your effort

File: src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java [hunk 5]
```diff
@@ -6,23 +6,28 @@
...
             formatLabel.andThen(label -> ExternallyAvailableContent.Description.create("icon-pride", label));
 
     @Override
     public Collection<ExternallyAvailableContent> get(BaselineExperiment experiment) {
-        return singleton(new ExternallyAvailableContent(formatLink.apply(experiment), createIcon.apply(experiment)));
+        return  experiment.getSecondaryAccessions().isEmpty() ? Collections.emptyList() :
+                experiment.getSecondaryAccessions()
+                        .stream()
+                        .map(accession -> new ExternallyAvailableContent(formatLink.apply(accession), createIcon.apply(accession)))
+                        .collect(Collectors.toCollection(ArrayList::new));
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java]: Let's make this more readable for the later coming developers.
I am going to do another comment with the missing private methods.
See below...
```suggestion
        var secondaryAccessions = experiment.getSecondaryAccessions();

        if (!secondaryAccessions.isEmpty()) {
            return getExternallyAvailableContents(secondaryAccessions);
        } else {
            return emptyContent();
        }
```

File: src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java [hunk 6]
```diff
@@ -6,23 +6,28 @@
...
     }
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java:37]: Please add these private methods to the and of the class. Thanks
```suggestion
@NotNull
    private static List<ExternallyAvailableContent> emptyContent() {
        return Collections.emptyList();
    }

    @NotNull
    private static List<ExternallyAvailableContent> getExternallyAvailableContents(ImmutableSet<String> secondaryAccessions) {
        return secondaryAccessions.stream()
                .map(secondaryAccession -> new ExternallyAvailableContent(
                                formatLink.apply(secondaryAccession),
                                createIcon.apply(secondaryAccession)
                        )
                )
                .collect(Collectors.toList());
    }
```

**Review by ke4 — CHANGES_REQUESTED** [review]
Your code is doing that we discussed yesterday. Well done.
I just wanted to make it more clean and readable to the later coming developer, so I added some suggestions. You only have to click on the `Commit suggestions` button to make the commits.
We also need the modified test cases that we discussed today's status meeting.
Thanks for your work

File: src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java [hunk 7]
```diff
@@ -16,7 +18,7 @@
 public class ExternallyAvailableContentService<E extends Experiment> {
 
     private final List<ExternallyAvailableContent.Supplier<E>> suppliers;
-
+    private static final Logger LOGGER = LoggerFactory.getLogger(ExternallyAvailableContentService.class);
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java]: You added this `LOGGER`, but you are not using it.
Could you please remove it, if it is not needed.
If it was a temporary addition that's exactly what you can achieve with IntelliJ's non-suspending logging in the Debugger.
Thanks

File: src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java [hunk 8]
```diff
@@ -39,7 +41,7 @@ public Function<HttpServletResponse, Void> stream(E experiment, final URI uri) {
 
     public List<ExternallyAvailableContent> list(final E experiment,
                                                  final ExternallyAvailableContent.ContentType contentType) {
-        return suppliers.stream()
+       return   suppliers.stream()
```
Comment (ke4) [inline src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java]: Probably you added these 2 spaces accidentally.

File: src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java [hunk 9]
```diff
@@ -44,6 +44,43 @@ void iconAndLinkPointAtPride() throws URISyntaxException {
...
+        when(baselineExperimentMock.getSecondaryAccessions()).thenReturn(ImmutableSet.of(accession1, accession2));
+        var result = subject.get(baselineExperimentMock);
+
+        assertThat(result).hasSize(2);
+
+        assertThat(result)
+                .element(0)
+                .hasFieldOrPropertyWithValue(
+                        "uri",
+                        new URI("redirect:https://www.ebi.ac.uk/pride/archive/projects/" + accession1))
```
Comment (ke4) [inline src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java]: You can extract `"redirect:https://www.ebi.ac.uk/pride/archive/projects/"` to a class level constant and use it in the previous method, too.

File: src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java [hunk 10]
```diff
@@ -44,6 +44,43 @@ void iconAndLinkPointAtPride() throws URISyntaxException {
...
+                .hasFieldOrPropertyWithValue(
+                        "description",
+                        ExternallyAvailableContent.Description.create("icon-pride", "PRIDE Archive: project " + accession1));
```
Comment (ke4) [inline src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java]: You can extract ""PRIDE Archive: project "" to a class level constant and use it in the previous method, too.

**Review by ke4 — CHANGES_REQUESTED** [review]
I added some tiny comments. Could you fix them, please?
Otherwise good to go.
Thanks

**Review by ke4 — APPROVED** [review]
LGTM!
Thanks for your work
